services:
 app:
    tty: true
    networks:
      - app_network
    build:
      context: ./next-stock
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./next-stock:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - db
 db:
   image: postgres:15
   hostname: db
   env_file:
     - ./next-stock/.env
   networks:
     - app_network
   environment:
     - TZ=Etc/UTC
     - POSTGRES_DB=mydb
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=password
     - PGDATA=/var/lib/postgresql/data/pgdata
   ports:
     - 5432:5432
   volumes:
     - ./postgresql/data:/var/lib/postgresql/data
     - ./sql:/docker-entrypoint-initdb.d

networks:
 app_network:
   driver: bridge